############################################################################
##  Base `configuration.yaml` most stuff is in packages/*.yaml
############################################################################
homeassistant:
  auth_providers:
  - type: homeassistant
  # Uncomment next line if you want to enable legacy API password support
  - type: legacy_api_password
  #- type: trusted_networks
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 330
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages
  
############################################################################
http:
  api_password: !secret http_password
  base_url: 127.0.0.1
#USE NGINX  
  #ssl_certificate: !secret ssl_certificate
  #ssl_key: !secret ssl_key
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24
  login_attempts_threshold: 5
  ip_ban_enabled: false
############################################################################
# Show links to resources in log and frontend
#introduction:
# Enables the frontend
frontend:
# Enables configuration UI
config:
# Enables support for tracking state changes over time
history:
# View all events in a logbook
logbook:
# Enables a map showing the location of tracked devices
map:

#cloud:
#updater:
#discovery:
#conversation:

###############################################
#https://home-assistant.io/components/recorder/
recorder:
  purge_interval: 2
  purge_keep_days: 3
  include:
    domains:
      - sensor
      - switch
     # - light 
     #- media_player
##############################################
#https://home-assistant.io/components/logger/
logger:
  default: error
  logs:
    homeassistant.components.rflink: warning
    #homeassistant.components.sensor.template: critical
    #homeassistant.components.cover: critical
    #homeassistant.components.telegram_bot: debug
    #mysensors: debug
    #homeassistant.components.light: error
    #homeassistant.components.mysensors: error
    #homeassistant.components.mqtt: error
    #homeassistant.core: info
    #homeassistant.components.tts: debug
    #homeassistant.components.media_player: debug
    #homeassistant.components.cloudflare: error
    #homeassistant.components.switch: debug
    #rflink: debug
    #tts: debug

###################################################
#https://www.home-assistant.io/components/panel_iframe/
#packages/data_visualization.yaml

####################################################
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/splitting_configuration/

group: !include groups.yaml
alarm_control_panel: !include alarm.yaml
panel_custom: !include panel_custom.yaml

####################################################
cloudflare:
  email: gpammendola@yahoo.it
  api_key: !secret cloudflare_api
  zone: jump2000.it
  records:
    - domo
    - www
    - grafana
    - webterminal

####################################################
#                                                  #
#                 GATEWAY - HUBS                   #
#                                                  #
####################################################
mysensors:
  gateways:
    - device: '192.168.1.103'
      persistence_file: '/home/homeassistant/.homeassistant/mysensors.json'
      tcp_port: 5003
  optimistic: false
  persistence: true
  version: '2.2'
#------------------------------------
rflink:
  port: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
  wait_for_ack: False
  ignore_devices:
    - newkaku_*
    - digitech_*
    - oregontemp_*
    - auriol_*
    - firstline_*
    - bl999_*
    - mebus_*
    - alectov1_*
#------------------------------------
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    #- mac: !secret xiaomi_gateway1_mac
    - key: !secret xiaomi_key
#------------------------------------
hue:
  bridges:
    - host: 192.168.1.100
      allow_unreachable: true
      allow_hue_groups: true

####################################################
#                                                  #
#           END OF CONFIGURATION FILE              #
#                                                  #
####################################################