#################################################################
#                                                               #
#                        Packages/Camera                        #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'camera'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

####################################################
#                                                  #
#                    TELECAMERE                    #
#                                                  #
####################################################
 
#  - platform: generic
#    name: Telecamera Livia Maria
#    still_image_url: http://192.168.1.150/cgi-bin/currentpic.cgi?width=1920&height=1080
camera:
  - platform: generic
    name: Grafana Power Image
    still_image_url: 'http://192.168.1.101:3000/render/d-solo/680D0Azgz/sensori?orgId=1&panelId=6&from=1530736912474&to=1530823312475&width=600&height=300&tz=UTC%2B02%3A00&from=now-1d/d&to=now/d'
    username: !secret grafana_user
    password: !secret grafana_pass
  - platform: generic
    still_image_url: https://api.sat24.com/animated/IT/infraPolair/3/W_dot_%20Europe%20Standard%20Time/9263758  
    name: Telecamera IR
  - platform: generic
    still_image_url: https://api.sat24.com/animated/IT/rainTMC/3/W_dot_%20Europe%20Standard%20Time/6012921  
    name: Telecamera Pioggia
  - platform: local_file
    name: Grafana Energy Meter
    file_path: /home/homeassistant/.homeassistant/downloads/energymeter.png
  - platform: local_file
    name: Grafana Power Meter
    file_path: /home/homeassistant/.homeassistant/downloads/powermeter.png
  - platform: ffmpeg
    name: dafang2
    input: -rtsp_transport tcp -i rtsp://192.168.1.150:8554/unicast
  - platform: ffmpeg
    name: dafang1
    input: -rtsp_transport tcp -i rtsp://192.168.1.151:8554/unicast

####################################################
#                                                  #
#                    FFMPEG                        #
#                                                  #
####################################################
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg
#################################################################
#                                                               #
#                           Sensori                             #
#                                                               #
#################################################################
####################################################
#                                                  #
#                  DAFANG STATUS                   #
#                                                  #
####################################################
sensor:  
  - platform: mqtt
    state_topic: "myhome/dafang1"
    name: "dafang1"
    json_attributes:
      - uptime
      - ssid
      - bitrate
      - signal_level
      - link_quality
      - noise_level

  - platform: mqtt
    state_topic: "myhome/dafang2"
    name: "dafang2"
    json_attributes:
      - uptime
      - ssid
      - bitrate
      - signal_level
      - link_quality
      - noise_level
#################################################################
#                                                               #
#                          Automation                           #
#                                                               #
#################################################################
automation:
  - alias: Rilevamento movimenti e invio foto
    hide_entity: true
    trigger:
    - entity_id: group.pir_sensors
      platform: state
      to: 'on'
    condition:
    - condition: state
      entity_id: sensor.gianpi
      state: 'Fuori'
    - condition: state
      entity_id: sensor.romi
      state: 'Fuori'
    - condition: state
      entity_id: alarm_control_panel.house
      state: armed_away
    action:
    - service: notify.telegram
      data_template:
        message: 'Rilevati Movimenti.'
        data: 
          photo:
            url: 'https://www.jump2000.it{{states.camera.dafang1.attributes.entity_picture}}'
            caption: '{{now().strftime("%d.%m.%Y-%H:%M:%S")}}'
    - service: notify.telegram
      data:
        title: '*-- ATTENZIONE --*'
        message: 'Rilevati Movimenti. Please check your home'
#################################################################
#                                                               #
#                  End of Configuration                         #
#                                                               #
#################################################################
