#################################################################
#                                                               #
#                       Packages/Sensori                        #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'cube'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## sensor
    ################################################

    sensor.0x00158d000269e844:
      <<: *customize
      friendly_name: CUBO Studio
    
    sensor.bat_cubo_studio:
      <<: *customize
      friendly_name: Cubo Studio
      icon: mdi:battery
      unit_of_measurement: "%"

    binary_sensor.0x00158d00023372ec:
      <<: *customize
      friendly_name: WATER Studio
    
    sensor.bat_water_studio:
      <<: *customize
      friendly_name: Water Studio
      icon: mdi:battery
      unit_of_measurement: "%"    

#################################################################
#                                                               #
#                            Sensor                             #
#                                                               #
#################################################################
sensor:
  - platform: template
    sensors:
      bat_cubo_studio:
        unit_of_measurement: "%" 
        value_template: '{{ state_attr("sensor.0x00158d000269e844", "battery") | int }}'

  - platform: template
    sensors:
      water_cubo_studio:
        unit_of_measurement: "%" 
        value_template: '{{ state_attr("binary_sensor.0x00158d00023372ec", "battery") | int }}'

#################################################################
#                                                               #
#                          Automation                           #
#                                                               #
#################################################################
automation:

####################################################
#                                                  #
#               XIAOMI WATER LEAK                  #
#                                                  #
####################################################
  - alias: segnalazione allagamento
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/0x00158d00023372ec'
    condition:
    - condition: template
      value_template: "{{ 'true' == trigger.payload_json.water_leak }}"
    action:
    - service: notify.telegram
      data_template:
        title: '* ATTENZIONE ALLAGAMENTO *'
        message: 'Controlla subito nello Studio'
####################################################
#                                                  #
#                  XIAOMI CUBE                     #
#                                                  #
####################################################
  - alias: aumenta luminosita paralume sala con cubo
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/0x00158d000269e844'
    condition:
    - condition: template
      value_template: "{{ 'rotate_right' == trigger.payload_json.action }}"
    - condition: state
      entity_id: light.yeelight_paralume_sala
      state: 'on'
    action:
    - service: light.turn_on
      entity_id: light.yeelight_paralume_sala
      data_template:
        brightness: >-
          {{ states.light.yeelight_paralume_sala.attributes.brightness | round(0) + 50 }}
####################################################
  - alias: diminuisce luminosita luce ingresso con cubo
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/0x00158d000269e844'
    condition:
    - condition: template
      value_template: "{{ 'rotate_left' == trigger.payload_json.action }}"
    - condition: state
      entity_id: light.yeelight_paralume_sala
      state: 'on'
    action:
      service: light.turn_on
      entity_id: light.yeelight_paralume_sala
      data_template:
        brightness: >-
          {{ states.light.yeelight_paralume_sala.attributes.brightness | round(0) - 50 }}
#################################################### 
  - alias: accende spegne TV LG con cubo
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/0x00158d000269e844'
    condition:
      condition: template
      value_template: "{{ 'shake' == trigger.payload_json.action }}"
    action:
      service: switch.toggle
      entity_id: switch.tv_lg
####################################################
  - alias: accende spegne luce sala con cubo
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/0x00158d000269e844'
    condition:
      condition: template
      value_template: "{{ 'tap' == trigger.payload_json.action }}"
    action:
      service: light.toggle
      entity_id: light.luci_sala
####################################################
  - alias: accende spegne luce studio con cubo
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/0x00158d000269e844'
    condition:
      condition: template
      value_template: "{{ 'flip90' == trigger.payload_json.action }}"
    action:
      service: light.toggle
      entity_id: light.yeelight_luce_studio
####################################################
  - alias: accende spegne luci bedroom con cubo
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/0x00158d000269e844'
    condition:
      condition: template
      value_template: "{{ 'flip180' == trigger.payload_json.action }}"
    action:
      service: light.toggle
      entity_id: group.bedroom_lights
####################################################
  - alias: accende spegne luce ingresso con cubo
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/0x00158d000269e844'
    condition:
      condition: template
      value_template: "{{ 'slide' == trigger.payload_json.action }}"
    action:
      service: light.toggle
      entity_id: light.xiaomi_philips_ingresso 
#################################################################
#                                                               #
#                             END                               #
#                                                               #
#################################################################