#################################################################
#                                                               #
#                       Packages/Presence                       #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'cumulative'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

#################################################################
#                                                               #
#                           Group                               #
#                                                               #
################################################################# 
    
#################################################################
#                                                               #
#                          Sensors                              #
#                                                               #
################################################################# 

sensor:
#consumo giornaliero di energia elettrica       
  - platform: template
    sensors:
      energy_day:
        friendly_name: "Daily Energy"
        value_template: >
          {{ (float(states.sensor.jmp_energy_12_12_2.state) - float(states.input_number.midnight_energy.state)) | round(2) }}
        unit_of_measurement: 'kWh'
        icon_template: mdi:flash-outline        

#--------------------------------------------------- 
#accumulo giornaliero di pioggia 
  - platform: template
    sensors:
      rain_day:
        friendly_name: "Daily Rain"
        value_template: >
          {{ (float(states.sensor.jmp_rain_17_17_3.state) - float(states.input_number.midnight_rain.state)) | round (2) }}
        unit_of_measurement: 'mm'
        icon_template: mdi:water

  - platform: file
    name: energy mezzanotte
    file_path: /home/homeassistant/.homeassistant/energylog.txt

  - platform: file
    name: rain mezzanotte
    file_path: /home/homeassistant/.homeassistant/rainlog.txt   
#################################################################
#                                                               #
#                       input number                            #
#                                                               #
#################################################################
input_number:
  midnight_energy:
    name: Midnight Power Level
    min: 0
    max: 999999999
 
  midnight_rain:
    name: Midnight Rain Level
    min: 0
    max: 999999999
#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################
# scrive su file i valori giornalieri del sensore
automation:
  - alias: 'Energy Rain Start of the day value'
    trigger:
      platform: time
      at: '00:00:00'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.midnight_energy
          value: "{{ states.sensor.jmp_energy_12_12_2.state }}"
      - service: notify.energy
        data_template:
          message: "{{ states.sensor.jmp_energy_12_12_2.state }} kWh"
      - service: input_number.set_value
        data_template:
          entity_id: input_number.midnight_rain
          value: "{{ states.sensor.jmp_rain_17_17_3.state }}"
      - service: notify.rain
        data_template:
          message: "{{ states.sensor.jmp_rain_17_17_3.state }} mm"

#---------------------------------------------------
  - alias: 'Rain and Energy Update'
    initial_state: true
    trigger:
      platform: time
      minutes: '/4'
    action:
      - service: homeassistant.update_entity
        entity_id: 
        - sensor.rain_day
        - sensor.energy_day

#---------------------------------------------------
  - alias: 'Startup Daily sensor'
    trigger:
      platform: homeassistant
      event: start
    action: 
      - service: input_number.set_value
        data_template:
          entity_id: input_number.midnight_rain
          value: '{{ states.sensor.rain_mezzanotte.state.split(" ")[1]|float(2) }}'
      - service: input_number.set_value
        data_template:
          entity_id: input_number.midnight_energy
          value: '{{ states.sensor.energy_mezzanotte.state.split(" ")[1]|float(2) }}'

#################################################################
#                                                               #
#                     NOTIFY IF WATT >4000                      #
#                                                               #
#################################################################

  - alias: 'Notify if watt major 4000'
    trigger:
      - platform: numeric_state
        above: 4000
        entity_id:
          - sensor.jmp_energy_12_12_1
        value_template: '{{ states.sensor.jmp_energy_12_12_1.state }}'
    action:
      - service: notify.telegram
        data_template:
          title: "- ATTENZIONE POTENZA ELEVATA -"
          message: "Consumo corrente: {{ states.sensor.jmp_energy_12_12_1.state }} Watt"
      - service: media_player.volume_set
        data:
          entity_id: media_player.salotto
          volume_level: 0.4
      - service: tts.google_say
        entity_id: media_player.salotto
        data_template: 
          message: >-
            {{ [
            "Attenzione potenza elevata, spegnere il forno" ,
            "Attenzione consumo elevato, spegnere qualche elettromodestico " ,
            ] |random }}
      - delay: '00:020:00'
      - service: tts.google_say
        entity_id: media_player.salotto
        data_template: 
          message: >-
            {{ [
            "Attenzione potenza elevata, spegnere il forno" ,
            "Attenzione consumo elevato, spegnere qualche elettromodestico " ,
            ] |random }}

#################################################################
#                                                               #
#                  END OF CONFIGURATION FILE                    #
#                                                               #
#################################################################