########################################################################
### Meteo DarkSky
########################################################################
# Aggiungere le icone in presenti nello .zip
# /home/homeassistant/.homeassistant/www/icons/dark_sky/


################################################
## Customization
################################################
homeassistant:
  customize_glob:
    sensor.dark_sky_temperature:
      friendly_name: Temperatura
    sensor.dark_sky_humidity:
      friendly_name: Umidità
    sensor.dark_sky_wind_speed:
      friendly_name: Velocità Vento
    sensor.dark_sky_precip_intensity:
      friendly_name: Intensità Precipitazioni
    sensor.dark_sky_precip_probability:
      icon: mdi:weather-lightning-rainy
      friendly_name: Probabilità Precipitazioni

################################################
## Group
################################################

group:
  meteo_darksky:
    name: Condizioni Meteo
    entities:
      - sensor.data_ora
      - sensor.dark_sky_summary_tmpl
      - sensor.dark_sky_temperature
      - sensor.dark_sky_humidity
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_dir
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_hourly_summary_tmpl

  previsioni_darksky:
    name: Previsioni Meteo
    icon: mdi:sun
    entities:
      - sensor.forecast_0
      - sensor.forecast_1
      - sensor.forecast_2
      - sensor.forecast_3
      - sensor.forecast_4
      - sensor.forecast_5
      - sensor.forecast_6
      - sensor.forecast_7     

################################################
## Sensor
################################################
sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    latitude: 43.317380 # mettete le vostre coordinate
    longitude: 11.312202 # mettete le vostre coordinate
    language: it
    forecast:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    monitored_conditions:
      - summary
      - icon
      - temperature
      - temperature_min
      - temperature_max
      - apparent_temperature
      - humidity
      - hourly_summary
      - daily_summary
      - precip_probability
      - precip_intensity
      - wind_bearing
      - wind_speed
      - pressure
################################################
## platform template
################################################
  - platform: template
    sensors:
      dark_sky_summary_tmpl:
        friendly_name_template: Condizione
        value_template: >
          {{ states('sensor.dark_sky_summary') }}
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon.state ~ '.png'}}
      dark_sky_hourly_summary_tmpl:
        friendly_name_template: Condizione Giornaliera
        value_template: >
          {{ states('sensor.dark_sky_hourly_summary') }}
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_hourly_summary.attributes.entity_picture | replace("/static/images/darksky/","") | replace(".svg","") ~ '.png'}}
      
      dark_sky_wind_dir:
        friendly_name: 'Direzione Vento'
        value_template: >-
          {% set wind_dir = states.sensor.dark_sky_wind_bearing.state %}
          {% if wind_dir | float<=23 %}Nord [Tramontana]
          {% elif wind_dir | float>338 %}Nord [Tramontana]
          {% elif 23 < (wind_dir|float) <=68 %}NE [Grecale]
          {% elif 68 < (wind_dir|float) <=113 %}Est [Levante]
          {% elif 113 < (wind_dir|float) <=158 %}SE [Scirocco]
          {% elif 158 < (wind_dir|float) <=203 %}Sud [Ostro/Mezzogiorno]
          {% elif 203 < (wind_dir|float) <=248 %}SO [Libeccio/Garbino]
          {% elif 248 < (wind_dir|float) <=293 %}Ovest [Ponente]
          {% elif 293 < (wind_dir|float) <=338 %}NO [Maestrale]
          {%- endif %}
        icon_template: mdi:compass
      
      forecast_0:
        friendly_name_template: Giorno
        value_template: Max | Min | Pioggia
        icon_template: mdi:weather-partlycloudy
      forecast_1:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (1 * 86400 ) -%}
          {% set giorno = ["Domenica", "Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato"] %}
          {% set mese = ["Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"] %}
          {% set m_ok = date | timestamp_custom("%m") | int %}
          {% set g_ok = date | timestamp_custom("%w") | int %}
          {{giorno[g_ok] + ' ' + date | timestamp_custom("%d") + ' ' + mese[m_ok - 1]}}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_1.state|round(0)}}°|{{states.sensor.dark_sky_daily_low_temperature_1.state|round(0)}}°|{{states.sensor.dark_sky_precip_probability_1.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_1.state ~ '.png'}}
      forecast_2:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (2 * 86400 ) -%}
          {% set giorno = ["Domenica", "Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato"] %}
          {% set mese = ["Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"] %}
          {% set m_ok = date | timestamp_custom("%m") | int %}
          {% set g_ok = date | timestamp_custom("%w") | int %}
          {{giorno[g_ok] + ' ' + date | timestamp_custom("%d") + ' ' + mese[m_ok - 1]}}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_2.state|round(0)}}°|{{states.sensor.dark_sky_daily_low_temperature_2.state|round(0)}}°|{{states.sensor.dark_sky_precip_probability_2.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_2.state ~ '.png'}}
      forecast_3:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (3 * 86400 ) -%}
          {% set giorno = ["Domenica", "Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato"] %}
          {% set mese = ["Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"] %}
          {% set m_ok = date | timestamp_custom("%m") | int %}
          {% set g_ok = date | timestamp_custom("%w") | int %}
          {{giorno[g_ok] + ' ' + date | timestamp_custom("%d") + ' ' + mese[m_ok - 1]}}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_3.state|round(0)}}°|{{states.sensor.dark_sky_daily_low_temperature_3.state|round(0)}}°|{{states.sensor.dark_sky_precip_probability_3.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_3.state ~ '.png'}}
      forecast_4:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (4 * 86400 ) -%}
          {% set giorno = ["Domenica", "Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato"] %}
          {% set mese = ["Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"] %}
          {% set m_ok = date | timestamp_custom("%m") | int %}
          {% set g_ok = date | timestamp_custom("%w") | int %}
          {{giorno[g_ok] + ' ' + date | timestamp_custom("%d") + ' ' + mese[m_ok - 1]}}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_4.state|round(0)}}°|{{states.sensor.dark_sky_daily_low_temperature_4.state|round(0)}}°|{{states.sensor.dark_sky_precip_probability_4.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_4.state ~ '.png'}}
      forecast_5:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (5 * 86400 ) -%}
          {% set giorno = ["Domenica", "Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato"] %}
          {% set mese = ["Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"] %}
          {% set m_ok = date | timestamp_custom("%m") | int %}
          {% set g_ok = date | timestamp_custom("%w") | int %}
          {{giorno[g_ok] + ' ' + date | timestamp_custom("%d") + ' ' + mese[m_ok - 1]}}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_5.state|round(0)}}°|{{states.sensor.dark_sky_daily_low_temperature_5.state|round(0)}}°|{{states.sensor.dark_sky_precip_probability_5.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_5.state ~ '.png'}}
      forecast_6:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (6 * 86400 ) -%}
          {% set giorno = ["Domenica", "Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato"] %}
          {% set mese = ["Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"] %}
          {% set m_ok = date | timestamp_custom("%m") | int %}
          {% set g_ok = date | timestamp_custom("%w") | int %}
          {{giorno[g_ok] + ' ' + date | timestamp_custom("%d") + ' ' + mese[m_ok - 1]}}
        value_template: >
            {{states.sensor.dark_sky_daily_high_temperature_6.state|round(0)}}°|{{states.sensor.dark_sky_daily_low_temperature_6.state|round(0)}}°|{{states.sensor.dark_sky_precip_probability_6.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_6.state ~ '.png'}}
      forecast_7:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (7 * 86400 ) -%}
          {% set giorno = ["Domenica", "Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato"] %}
          {% set mese = ["Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"] %}
          {% set m_ok = date | timestamp_custom("%m") | int %}
          {% set g_ok = date | timestamp_custom("%w") | int %}
          {{giorno[g_ok] + ' ' + date | timestamp_custom("%d") + ' ' + mese[m_ok - 1]}}
        value_template: >
            {{states.sensor.dark_sky_daily_high_temperature_7.state|round(0)}}°|{{states.sensor.dark_sky_daily_low_temperature_7.state|round(0)}}°|{{states.sensor.dark_sky_precip_probability_7.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_7.state ~ '.png'}}

########################################################################
########################################################################
