#################################################################
#                                                               #
#                       Packages/Presence                       #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################



#################################################################
#                                                               #
#                           Group                               #
#                                                               #
################################################################# 
automation:
#########################################################
#                                                       #
#                NOTIFY FIRE ALARM                      #
#                                                       #
#########################################################

  - alias: 'Send notification on fire alarm'
    trigger:
      platform: state
      entity_id: binary_sensor.smoke_sensor_158d0001574899
      from: 'off'
      to: 'on'
    action:
    - service: notify.telegram
      data:
        message: 'ATTENZIONE - Allarme incendio!!'
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: F0B429B45C97
        ringtone_id: 5
        ringtone_vol: 100

#########################################################
#                                                       #
#              END OF CONFIGURATION FILE                #
#                                                       #
#########################################################