#################################################################
#                                                               #
#                      Packages/Weather                         #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    binary_sensor.ha_update_available:
      icon: mdi:cloud-download
    binary_sensor.new_podcast_available:
      icon: mdi:podcast

#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:
  firmware:
    name: Firmware Status
    view: no
    entities:
      - binary_sensor.ha_update_available
#      - binary_sensor.new_podcast_available

#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################
sensor:
#########################  HA Version  ##########################
## Check HA Version Installed    
  - platform: command_line
    name: Installed HA Version
    command: "head -5 /home/homeassistant/.homeassistant/.HA_VERSION"
## Check Latest HA Version    
  - platform: rest
    resource: https://pypi.python.org/pypi/homeassistant/json
    name: Latest HA Version
    value_template: "{{ value_json.info.version }}"
    scan_interval: 3600
    
#########################  HA Podcast  ##########################
## Check Latest HA Podcast
#  - platform: scrape
#    resource: https://hasspodcast.io/feed/podcast
#    name: Latest HA Podcast
#    select: 'enclosure:nth-of-type(1)'
#    value_template: '{{ value.split("/")[5] }}'
#    attribute: url
    
## Check Latest Watched Podcast
#  - platform: template
#    sensors:
#      latest_watched_podcast:
#        value_template: '{% if is_state("sensor.latest_ha_podcast", "ha028.mp3") %}ha028.mp3{% else %}On{% endif %}'

###########  Compare Latest Against Current Version  ############
binary_sensor: 
#########################  HA Podcast  ##########################   
#  - platform: template
#    sensors:
#      new_podcast_available:
#        value_template: >-
#          {{ states.sensor.latest_ha_podcast.state != states.sensor.latest_watched_podcast.state and states.sensor.latest_ha_podcast.state != 'unavailable' }}
#        friendly_name: New Podcast Available

#########################  HA Update  ###########################
  - platform: template
    sensors:
      ha_update_available:
        value_template: >-
          {{ states.sensor.latest_ha_version.state != states.sensor.installed_ha_version.state and states.sensor.latest_ha_version.state != 'unavailable' }}
        friendly_name: HA Update Available

#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

automation:
## Notify of New HA Update Available
  - alias: HA Update Available Notification
    trigger:
      platform: state
      entity_id: binary_sensor.ha_update_available
      to: 'on'
    action:
      - service: notify.telegram
        data:
          message: 'New Update Available for HA - https://www.home-assistant.io'

## Notify of New HA Podcast
#  - alias: HA Podcast Update Available Notification
#    trigger:
#      platform: state
#      entity_id: binary_sensor.new_podcast_available
#      to: 'on'
#    action:
#      - service: notify.telegram
#        data:
#          message: 'New Podcast Available for HA - https://hasspodcast.io/feed/podcast'