# CONF GOOGLE
#################################################################
#                                                               #
#                       Packages/Sensori                        #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'googleass'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false


#################################################################
#                                                               #
#                          Google Home                          #
#                                                               #
#################################################################

google_assistant:
  project_id: !secret progettoGH
  api_key: !secret apikeyGH
  expose_by_default: false
  #exposed_domains:
  #  - switch
  #  - light
  # - group
  entity_config:
    light.bedroom:
      name: luci stanza da letto
      room: camera da letto
      expose: true
      aliases:
        - Luci bedroom
        - luci camera da letto
    light.hue_color_lamp_1:
      room: camera da letto
      name: luce camera 1
      expose: true
      aliases:
        - Luce camera uno
    light.hue_color_lamp_2:
      room: camera da letto
      name: luce camera 2
      expose: true
      aliases:
        - Luce camera due
    light.hue_color_lamp_3:
      room: camera da letto
      name: luce camera 3
      expose: true
      aliases:
        - Luce camera tre
    light.hue_lightstrip_plus_1:
      room: camera da letto
      name: luce camera strip
      expose: true
      aliases:
        - Luce camera striscia
        - luce camera striscia led
    group.lampadario_bedroom:
      room: camera da letto
      name: luce lampadario
      expose: true
      aliases:
        - Lampadario Bedroom
        - Luce lampadario
    light.yeelight_luce_bedside:
      room: camera da letto
      name: luce camera gianpi
      expose: true
      aliases:
        - Luce Bedside
        - luce bedside comodino
    light.xiaomi_philips_bedroom:
      room: camera da letto
      name: luce romina
      expose: true
      aliases:
        - Paralume Romina
    light.gateway_light_f0b429b45c97:
      room: entrata
      name: luce gateway ingresso
      expose: true
      aliases:
        - Luce gateway entrata
    light.xiaomi_philips_ingresso:
      room: entrata
      name: luce ingresso
      expose: true
      aliases:
        - Paralume Ingresso
        - luce entrata
    light.yeelight_paralume_sala:
      room: salotto
      name: luce sala
      expose: true
      aliases:
        - Paralume Sala
        - paralume salotto
    light.yeelight_luce_studio:
      room: studio
      name: luce studio
      expose: true
      aliases:
        - Luce nello Studio
        - luce camera ospiti
    light.applique_sala:
      room: salotto
      name: lampadario salotto
      expose: true
      aliases:
        - Applique Sala
        - applique salotto
        - lampadario sala
    light.applique_livia:
      room: camera livia
      name: lampadario Livia
      expose: true
      aliases:
        - Applique Livia
        - applique camera Livia
    group.sala_lights:
      room: salotto
      name: luci salotto
      expose: true
      aliases:
        - Luci Sala
    group.studio_lights:
      room: studio
      name: luci studio
      expose: true
      aliases:
        - Luci Studio
    switch.tv_lg:
      room: salotto
      name: TV LG
      expose: true
      aliases:
        - TV sala
        - TV salotto
    switch.tv_lg_input:
      room: salotto
      name: Input TV LG
      expose: true
      aliases:
        - Input TV Sala
        - Input TV salotto
    switch.tv_lg_canali:
      room: salotto
      name: Canale TV LG
      expose: true
      aliases:
        - Canale TV Sala
        - canale TV salotto
    switch.tv_lg_volume:
      room: salotto
      name: Volume TV LG
      expose: true
      aliases:
        - Volume TV Sala
        - volume TV salotto
    switch.tv_lg_mute:
      room: salotto
      name: Muto TV LG
      expose: true
      aliases:
        - Muto TV Sala
        - muto TV salotto
    switch.orviboplug1:
      room: salotto
      name: Presa Orvibo
      expose: true
      aliases:
        - Presa Sala
        - presa salotto
    climate.daikin_fx_sala:
      room: salotto
      name: Condizionatore sala
      expose: true
      aliases:
        - Split Sala
        - split salotto
    climate.netatmo1:
      room: entrata
      name: Termostato
      expose: true
      aliases:
        - Termostato Ingresso
        - termostato caldaia
        - riscaldamento
    climate.valvola_salotto1:
      room: salotto
      name: Valvola Salotto 1
      expose: true
      aliases:
        - Valvola Sala 1
        - valvola salotto uno  
    climate.valvola_salotto2:
      room: salotto
      name: Valvola Salotto 2
      expose: true
      aliases:
        - Valvola Sala 2
        - valvola salotto due
    climate.valvola_studio:
      room: studio
      name: Valvola Studio
      expose: true
      aliases:
        - Valvola Studio
   
#################################################################
#                                                               #
#                          Automation                           #
#                                                               #
#################################################################
automation:
  - alias: Set GA Volume To Low At Night
    trigger:
      platform: time
      hours: 21
      minutes: 1
      seconds: 0
    action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.salotto
        volume_level: 0.20
#    - service: notify.telegram
#      data_template:
#        title: "-- Google Home --"
#        message: 'Volume Google Home 20%'

  - alias: Set GA Volume To High Daytime
    trigger:
      platform: time
      hours: 9
      minutes: 1
      seconds: 0
    action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.salotto
        volume_level: 0.4
#    - service: notify.telegram
#      data_template:
#        title: "-- Google Home --"
#        message: 'Volume Google Home 40%'