#################################################################
#                                                               #
#                       Packages/Presence                       #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'mqtt_conf'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

#################################################################
#                                                               #
#                             MQTT                              #
#                                                               #
#################################################################

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  birth_message:
    topic: 'homeassistant/status'
    payload: 'online'
  will_message:
    topic: 'homeassistant/status'
    payload: 'offline'
  client_id: home-assistant
  username: !secret mqtt_user
  password: !secret mqtt_pass
  discovery: true
  discovery_prefix: homeassistant
  keepalive: 60
#################################################################
#                                                               #
#                           Sensori                             #
#                                                               #
################################################################# 
sensor:
### MQTT invalid config - mosquitto not running properly ###
  - platform: template
    sensors:
      mqtt_offline:
        value_template: >-
          {% if [mqtt] in states.persistent_notification.invalid_config.state %}
              Yes
          {% else %}
              No
          {% endif %}

#################################################################
#                                                               #
#                         SCRIPT / SHELL                        #
#                                                               #
################################################################# 
### Mosquitto + Home Assistant restart ###
script:
  mosquitto_hass_fix:
    alias: "Mosquitto + Home Assistant restart"
    sequence:
      - service: shell_command.mosquitto_hass_fix

shell_command:
### Mosquitto + Home Assistant restart ###
  mosquitto_hass_fix: "sudo service mosquitto restart && sudo systemctl restart home-assistant@homeassistant.service"

#For user homeassistant to be able to run these commands, I needed to add the following file in /etc/sudoers.d
#Cmnd_Alias MYSHELL = /usr/sbin/service, /bin/systemctl
#homeassistant ALL=(ALL)NOPASSWD:MYSHELL
#################################################################
#                                                               #
#                         Automation                            #
#                                                               #
################################################################# 
automation:
### If Mosquitto config fails, notify and restart mosquitto and then HASS ###
  - alias: 'Restart if Mosquitto not OK'
    trigger:
      platform: state
      entity_id: 'sensor.mqtt_offline'
      to: 'Yes'
    action:
      - delay:
          seconds: 60
      - service: notify.telegram
        data:
          title: '*Home Assistant issue*'
          message: 'Home Assistant will be restarted as MQTT was not running properly.'
#      - service: script.mosquitto_hass_fix

#################################################################
#                                                               #
#                             END                               #
#                                                               #
#################################################################